function init(self)
	msg.post("#camera", "acquire_camera_focus")
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("mouse_wheel_up") then
		local position = go.get_position(".")
		position.z = position.z - 10
		go.set_position(position)
	elseif action_id == hash("mouse_wheel_down") then
		local position = go.get_position(".")
		position.z = position.z + 10
		go.set_position(position)
	end
end