function init(self)
	self.lifeTime = .2
end

function final(self)
	-- Add finalization code here
	-- Remove this function if not needed
end

function update(self, dt)
	self.lifeTime = self.lifeTime - dt
	if self.lifeTime < 0 then
		-- Prevents if check from being called over and over
		self.lifeTime = 1000
		go.delete()
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		if message.group == hash("enemy") then
			go.delete(message.other_id)
			print("hit " .. sender)
		end
	end
end

function on_input(self, action_id, action)
	-- Add input-handling code here
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Remove this function if not needed
end
